// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksdrrdjdpcavvbjqjasv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZHJyZGpkcGNhdnZianFqYXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1ODMzOTQsImV4cCI6MjA1MzE1OTM5NH0.CSk0l9u_L4bsSgmdalwcIkiV9IIhRz9l7FW-N4BsA-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);